[package]
name = "arch"
version = "0.1.0"
edition = "2024"

[dependencies]
# Bevy
bevy = { version = "0.15.3", features = ["dynamic_linking", "trace_tracy"] }

# Bevy crates
iyes_perf_ui = "0.4.0"
bevy-inspector-egui = "0.30.0"
bevy_enhanced_input = "0.9.0"
bevy_meshem = { git = "https://github.com/Adamkob12/Meshem" }
#bevy_meshem = { path = "../Meshem" }
avian3d = "0.2.1"

# Other
fast-surface-nets = "0.2.1"
rand = "0.9.1"
serde = "1.0.219"
mem_dbg = "0.3"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
