[package]
name = "arch"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15.3", features = ["trace_tracy"] }
bevy_meshem = { git = "https://github.com/Adamkob12/Meshem" }
#bevy_meshem = { path = "../Meshem" }
fast-surface-nets = "0.2.1"
rand = "0.9.1"
serde = "1.0.219"
avian3d = "0.2.1"

iyes_perf_ui = "0.4.0"
mem_dbg = "0.3"
bevy-inspector-egui = "0.30.0"
