[package]
name = "arch"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15.3"
bevy_meshem = "0.4"
fast-surface-nets = "0.2.1"
rand = "0.9"
serde = "1.0.219"

mem_dbg = "0.3"
bevy-inspector-egui = "0.30.0"